AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Stack contains network resources and exports endpoint to network

Parameters:
  CIDRVpcA:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for VpcA

  CIDRSubnetA:
    Type: String
    Default: 10.0.0.0/24
    Description: CIDR block for SubnetA

  CIDRSubnetB:
    Type: String
    Default: 10.0.2.0/24
    Description: CIDR block for SubnetB (white ips)

  CIDRSubnetC:
    Type: String
    Default: 10.0.3.0/24
    Description: CIDR block for SubnetB


Resources:
  VpcA:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref CIDRVpcA
      EnableDnsSupport: true
      EnableDnsHostnames: true

  SubnetA:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: us-east-1a
      CidrBlock: !Ref CIDRSubnetA
      VpcId: !Ref VpcA

  SubnetB:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: us-east-1b
      CidrBlock: !Ref CIDRSubnetB
      VpcId: !Ref VpcA
      MapPublicIpOnLaunch: true

  SubnetC:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: us-east-1a
      CidrBlock: !Ref CIDRSubnetC
      VpcId: !Ref VpcA

  InternetGatewayA:
    Type: "AWS::EC2::InternetGateway"
    Properties: 
      Tags:
        - Key: "Name"
          Value: "InternetGatewayA"

  GatewayAttachmentVpcA:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId: !Ref VpcA
      InternetGatewayId: !Ref InternetGatewayA

  RouteTableVpcA:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VpcA

  Route:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGatewayA
      RouteTableId: !Ref RouteTableVpcA

  RouteTableAssociationSubnetA:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTableVpcA
      SubnetId: !Ref SubnetA

  RouteTableAssociationSubnetB:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTableVpcA
      SubnetId: !Ref SubnetB

  RouteTableAssociationSubnetCB:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId: !Ref RouteTableVpcA
      SubnetId: !Ref SubnetC

  EIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc
    DependsOn: 
      - InternetGatewayA

Outputs:
  VpcA:
    Description: VpcA
    Value: !Ref VpcA
    Export:
      Name: VpcA

  SubnetA:
    Description: SubnetA
    Value: !Ref SubnetA
    Export:
      Name: "VpcASubnetA"

  SubnetB:
    Description: SubnetB (White Ips)
    Value: !Ref SubnetB
    Export:
      Name: "VpcASubnetB"

  SubnetC:
    Description: SubnetC
    Value: !Ref SubnetC
    Export:
      Name: "VpcASubnetC"

  EIP:
    Description: Entrypoint address for Jenkins
    Value: !Ref EIP
    Export:
      Name: "EIPVpcA"
